### PR TITLE
Add wikiann notebook

### PR DESCRIPTION
**Pull request by hSterz**
Added wikiann notebook and fixed typos in other notebooks.

### CODE REVIEW

**Review by calpt — APPROVED** [review]
Updated some formulations. Rest looks good to me.

**Comment by calpt** [comment]
@JoPfeiff maybe you can have a look at the WikiAnn notebook too.

**Comment by JoPfeiff** [comment]
lgtm

**Comment by JoPfeiff** [comment]
maybe just add the languages as variables so that it is easy to play around with different language combinations. 
we support as source language "en", "ja", "zh", and "ar".
As target we support all languages that we have bert-base-multilingual-cased language adapters for.

**Pull request merged**
