### PR TITLE
Add support for loading adapters from HuggingFace Model Hub

### PR DESCRIPTION
**Pull request by calpt**
WIP for adding HuggingFace's model hub as a second source for loading adapters. Implementation via https://github.com/huggingface/huggingface_hub.

## Example

Adapter: https://huggingface.co/calpt/adapter-bert-base-squad1

### Loading from HF Hub

```python
model = BertForSequenceClassification.from_pretrained("bert-base-uncased")
model.load_adapter("calpt/adapter-bert-base-squad1", source="hf")
```

### Loading (the same adapter) from AdapterHub
```python
model = BertForSequenceClassification.from_pretrained("bert-base-uncased")
model.load_adapter("squad1", config="houlsby", source="ah")  # source="ah" is default & can be omitted
```

### CODE REVIEW

**Comment by calpt** [comment]
Hi @osanseviero!

Looks great! Thanks for looking into this and let me know if you need anything else from our side.

**Comment by osanseviero** [comment]
Hey Calpt! Nothing else from your side at the moment until this PR is submitted. We're adding code snippets for adapter transformers which reads from `adapter_config.json` as discussed 🚀 🌔 . Feel free to take a look:

https://github.com/huggingface/huggingface_hub/pull/62

**Review by hSterz — APPROVED** [review]

**Comment by osanseviero** [comment]
From the Hub side, if you add `- adapter-transformers` to the tags, you get a working code snippet that uses `adapter_config.json`. Check out https://huggingface.co/calpt/adapter-bert-base-squad1 for example.

**Comment by calpt** [comment]
@osanseviero Looks great! Thanks so much for your support on this! We'll add some documentation on our side and release this with the next feature update.

**Pull request merged**
