### PR TITLE
Refactor example scripts to leverage config strings

### PR DESCRIPTION
**Pull request by calpt**
Depends on #465.

This PR adds the following changes:
- Outsource adapter training setup into setup_adapter_training() method
- Merge MultiLingAdapterArguments into AdapterArguments

Breaking changes:
- Removal of MultiLingAdapterArguments

### CODE REVIEW

**Comment by adapter-hub-bert** [comment]
This PR/issue depends on:
* adapter-hub/adapter-transformers#465
---
Automatically provided by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖).

**Comment by adapter-hub-bert** [comment]
This PR/issue depends on:
* ~~adapter-hub/adapter-transformers#465~~
---
Automatically provided by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖).

**Review by lenglaender — COMMENTED** [review]
When running `examples/pytorch/dependency-parsing/run_udp.py` I get this error:

```
Traceback (most recent call last):
  File "/home/leon/UKP/AdapterHub/adapter-transformers/examples/pytorch/dependency-parsing/run_udp.py", line 352, in <module>
    main()
  File "/home/leon/UKP/AdapterHub/adapter-transformers/examples/pytorch/dependency-parsing/run_udp.py", line 173, in main
    language = adapter_args.language
AttributeError: 'AdapterArguments' object has no attribute 'language'
```
Also regarding `examples/pytorch/dependency-parsing/run_udp.py`: Is there a reason why you did not replace the code under `# Setup adapters blocks` with the method `setup_adapter_training(..)` as in the other files?

**Comment by calpt** [comment]
Thanks, updated the udp script

**Review by lenglaender — APPROVED** [review]

**Pull request merged**
